### PR TITLE
Git ignore yarn lock

### PR DESCRIPTION
**Pull request by Swiip**

### CODE REVIEW

**Comment by econdepe** [comment]
We should not gitignore any of the lock files (yarn or npm). I think that was choice made for the developing phase, but now that beta is live we should take proper care of the versioning

**Comment by Swiip** [comment]
Indeed, `yarn.lock` and `package-lock.json` should not be ignored. But it will have an impact on the build process and right now, `package-lock.json` is ignored. Also, we should choose between npm or yarn as a reference but not keeping both.

Imho, we could ignore it temporarely, yet having the discussion of making the move of commiting a lock file. Perhaps, @dhoko will have an opinion?

**Comment by mmso** [comment]
Agree with @Swiip, since we are building with npm let's ignore `yarn.lock`

**Comment by dhoko** [comment]
> We should not gitignore any of the lock files (yarn or npm). I think that was choice made for the developing phase, but now that beta is live we should take proper care of the versioning

Until we make a release for the app we can ignore them, it's easier to manage if we have tags. And as @mmso says, we don't use yarn, so let's ignore it.

**Pull request merged**
